version: "3.9"

services:
  storage_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_service
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: always
