version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
